[package]
name = "crane"
version = "0.1.0"
edition = "2021"
rust-version = "1.62"

[dependencies]
lark = { path = "lark" }
ui = { path = "ui" }

[workspace]
members = ["lark", "ui"]

[[bin]]
name = "crane"
path = "ui/src/bin/crane.rs"

[[bin]]
name = "lark"
path = "lark/src/bin/lark.rs"